services:
  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    command: yarn start
    env_file:
      - .env
  products:
    build: ./products
    ports:
      - "4001:4000"
    command: yarn start
  reviews:
    build: ./reviews
    ports:
      - "4002:4000"
    command: yarn start
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
