name: Products Test
on:
  workflow_dispatch: {}
  pull_request:
    branches: [main]
    paths:
      - "products/**"

jobs:
  test-products:
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_GRAPH_REF: ${{ secrets.APOLLO_GRAPH_REF }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Check products
        run: |
          rover subgraph check $APOLLO_GRAPH_REF --schema ./products/schema.graphql --name products
