name: Reviews Publish
on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - "reviews/**"

jobs:
  publish-reviews:
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_GRAPH_REF: ${{ secrets.APOLLO_GRAPH_REF }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Publish reviews
        run: |
          rover subgraph publish $APOLLO_GRAPH_REF --schema ./reviews/schema.graphql --name reviews
